use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::model::{Architecture, Platform};

pub const PACKAGE_REAPER: &str = "reaper";
pub const PACKAGE_OSARA: &str = "osara";
pub const PACKAGE_SWS: &str = "sws";
pub const PACKAGE_REAPACK: &str = "reapack";
pub const PACKAGE_REAKONTROL: &str = "reakontrol";
pub const PACKAGE_JAWS_SCRIPTS: &str = "jaws-scripts";
pub const PACKAGE_FFMPEG: &str = "ffmpeg";
pub const PACKAGE_SURGE_XT: &str = "surge-xt";
pub const PACKAGE_APP2CLAP: &str = "app2clap";

/// Logical id of the embedded package manifest, reported by the portability
/// self-check. It's no longer a single file — the packages live in
/// per-package `*.json` files under `embedded/packages/`, gathered at compile
/// time (see `build.rs`).
pub const BUILTIN_PACKAGE_MANIFEST_ID: &str = "embedded/packages";

/// Schema version of the package manifest. Previously the `schema_version`
/// field of the mono `builtin-packages.json`; now that packages are split
/// into per-file specs there's no central document to carry it, so it lives
/// here and is stamped onto the gathered [`PackageManifest`].
pub const PACKAGE_MANIFEST_SCHEMA_VERSION: u32 = 1;

// `EMBEDDED_PACKAGE_SOURCES: &[(&str, &str)]` — (file name, JSON body) for
// every `embedded/packages/*.json`, generated by build.rs and sorted by file
// name (the numeric prefix controls order).
include!(concat!(env!("OUT_DIR"), "/embedded_packages.rs"));

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PackageSpec {
    pub id: String,
    pub display_name: String,
    pub display_name_key: String,
    pub display_description_key: String,
    pub package_kind: PackageKind,
    pub required: bool,
    pub recommended: bool,
    /// Optional host-conditional escalation of `recommended`. When the named
    /// host capability is present, the package's *effective* recommended
    /// state flips to `true` regardless of the manifest baseline. Today this
    /// promotes ReaKontrol from `recommended: false` to recommended-by-
    /// default on hosts that have Komplete Kontrol installed. Resolve via
    /// [`effective_recommended`] rather than reading this field directly.
    #[serde(default)]
    pub recommended_when: Option<HostCapability>,
    /// When `true`, the wizard must show a package-specific acknowledgement
    /// page and the CLI must require an explicit `--accept-<package>-notice`
    /// flag before RABBIT stages or launches the install of this package.
    /// Used today by ReaPack to surface its donation notice; defaults to
    /// `false` for everything else.
    pub requires_user_acknowledgement: bool,
    /// When `true`, the package can only be installed against a *standard*
    /// REAPER installation, not a portable one: it installs to a fixed
    /// system/per-user location outside any portable REAPER folder (Surge XT
    /// and JAWS scripts via vendor installers; app2clap into the per-user
    /// CLAP folder). The wizard disables this package's row on a portable
    /// target. Replaces what used to be a hardcoded package-id list in the UI.
    pub requires_standard_install: bool,
    pub supported_platforms: Vec<SupportedPlatform>,
    pub supported_architectures: Vec<Architecture>,
    /// Data-driven latest-version rule. When set, the version is resolved by
    /// the generic engine from manifest data rather than per-package Rust. See
    /// [`VersionRule`].
    pub version: Option<VersionRule>,
    pub detectors: Vec<PackageDetector>,
    pub install_steps: Vec<InstallStep>,
    pub uninstall_steps: Vec<UninstallStep>,
    pub backup_policy: BackupPolicy,
    pub user_plugin_prefixes: Vec<String>,
    pub user_plugin_suffixes: Vec<String>,
    /// The wizard UI group this package is listed under. See [`PackageCategory`].
    pub category: PackageCategory,
    /// Data-driven GitHub-release definition driving version + download.
    /// See [`GithubReleaseSpec`].
    pub github_release: Option<GithubReleaseSpec>,
    /// Data-driven non-GitHub artifact definition (scrape / fixed URL /
    /// max-major release). When set, the download is derived from this block;
    /// the version side still uses the `version` [`VersionRule`]. See
    /// [`HttpArtifactSpec`].
    pub http_artifact: Option<HttpArtifactSpec>,
    /// Data-driven rejetto-HFS definition driving both version and download
    /// (JAWS-for-REAPER scripts). See [`HfsListingSpec`].
    pub hfs_listing: Option<HfsListingSpec>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PackageManifest {
    pub schema_version: u32,
    pub packages: Vec<EmbeddedPackageSpec>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EmbeddedPackageSpec {
    pub id: String,
    pub display_name: String,
    pub display_name_key: String,
    pub display_description_key: String,
    #[serde(default)]
    pub package_kind: PackageKind,
    #[serde(default)]
    pub required: bool,
    pub recommended: bool,
    /// See [`PackageSpec::recommended_when`].
    #[serde(default)]
    pub recommended_when: Option<HostCapability>,
    #[serde(default)]
    pub requires_user_acknowledgement: bool,
    #[serde(default)]
    pub requires_standard_install: bool,
    #[serde(default = "all_supported_platforms")]
    pub supported_platforms: Vec<SupportedPlatform>,
    #[serde(default = "all_supported_architectures")]
    pub supported_architectures: Vec<Architecture>,
    #[serde(default)]
    pub version: Option<VersionRule>,
    #[serde(default)]
    pub detectors: Vec<PackageDetector>,
    #[serde(default)]
    pub install_steps: Vec<InstallStep>,
    #[serde(default)]
    pub uninstall_steps: Vec<UninstallStep>,
    #[serde(default)]
    pub backup_policy: BackupPolicy,
    pub user_plugin_prefixes: Vec<String>,
    pub user_plugin_suffixes: PlatformSuffixes,
    #[serde(default)]
    pub category: PackageCategory,
    #[serde(default)]
    pub github_release: Option<GithubReleaseSpec>,
    #[serde(default)]
    pub http_artifact: Option<HttpArtifactSpec>,
    #[serde(default)]
    pub hfs_listing: Option<HfsListingSpec>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum PackageKind {
    ReaperApp,
    #[default]
    UserPluginBinary,
    Keymap,
    ReapackPackage,
    /// Drop-in script files (e.g. `.jss`/`.jsb`) that a screen reader loads
    /// from a known per-user directory. Platform-gated: a package of this
    /// kind only appears in the wizard when the relevant screen reader is
    /// detected on the host (e.g. JAWS-for-REAPER scripts on Windows).
    ScreenReaderScripts,
}

/// Which UI group a package is listed under in the wizard's package tree.
/// `Core` packages (the default) are the REAPER accessibility stack shown
/// under "Packages"; `Additional` packages are optional extras that aren't
/// tied to REAPER itself (e.g. Surge XT, app2clap) and are shown under a
/// separate "Additional software" group. Defaults to `Core` so a package
/// without a `category` in the manifest stays in the main list.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
pub enum PackageCategory {
    #[default]
    Core,
    Additional,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SupportedPlatform {
    Windows,
    Macos,
}

/// Data-driven definition of a package distributed through GitHub releases,
/// read by BOTH the version side ([`crate::latest`]) and the download side
/// ([`crate::artifact`]). When a package carries one of these, adding or
/// maintaining it needs only this manifest block — no per-package Rust. It
/// is the generalization of the hand-written ReaKontrol/app2clap snapshot
/// parsers + resolvers into one parameterized engine.
///
/// A package sets exactly one artifact source — `github_release`,
/// `http_artifact`, or `hfs_listing` — enforced by [`validate_package_spec`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GithubReleaseSpec {
    /// `owner/name`, e.g. `jcsteh/app2clap`.
    pub repo: String,
    /// Which release to read: `/releases/latest` or `/releases/tags/<tag>`.
    pub release: GithubReleaseSelector,
    /// How to derive the version (from the tag, or from an asset filename).
    pub version_from: VersionSource,
    /// Per-platform (optionally per-arch) asset matchers used to pick the
    /// download. The version side ignores this — it reads `version_from`.
    pub assets: Vec<AssetSelector>,
    /// Spec-wide fallback for how the downloaded asset is handled. Optional:
    /// a package whose platforms need *different* kinds (Surge XT —
    /// `Installer` on Windows, `DiskImage` on macOS) leaves this `None` and
    /// sets [`AssetSelector::artifact_kind`] per asset instead. The resolved
    /// kind is `selector.artifact_kind.or(spec.artifact_kind)`; the load-time
    /// validator rejects a spec where neither is set for some asset.
    #[serde(default)]
    pub artifact_kind: Option<GithubArtifactKind>,
    /// Where the resolved file installs. Defaults to `UserPlugins`.
    #[serde(default)]
    pub install_destination: InstallDestination,
}

/// Which GitHub release a [`GithubReleaseSpec`] reads. Serializes as the
/// bare string `"latest"` or as `{ "tag": "<name>" }`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GithubReleaseSelector {
    /// `GET /repos/<repo>/releases/latest`.
    Latest,
    /// `GET /repos/<repo>/releases/tags/<tag>` — a fixed or rolling tag
    /// (e.g. `snapshots`). Assets are sorted by version; release date/order
    /// is never trusted.
    Tag(String),
}

/// How a [`GithubReleaseSpec`] derives the package version. Serializes as
/// `{ "tag_name": { … } }` or `{ "asset_name": { … } }`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VersionSource {
    /// The release's `tag_name`, optionally with a leading `v` stripped
    /// (ReaPack's `v1.2.6` → `1.2.6`).
    TagName {
        #[serde(default)]
        strip_v_prefix: bool,
    },
    /// The version embedded in the highest-sorting asset filename. The
    /// prefix/suffix to strip come from the matching [`AssetSelector`] (so a
    /// multi-platform package like ReaKontrol, whose Windows and macOS
    /// assets carry different prefixes, needs no per-platform version rule);
    /// `strip_trailing_dot_segment` additionally drops a trailing
    /// `.<segment>` (the short commit hash in
    /// `app2clap_2026.5.17.34.b6f558cf.zip`).
    AssetName {
        #[serde(default)]
        strip_trailing_dot_segment: bool,
    },
}

/// A per-platform (and optionally per-arch) rule for selecting the release
/// asset to download. Exactly one of (`name_prefix` + `name_suffix`) or
/// `exact_name` must be set — enforced at manifest load.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssetSelector {
    pub platform: SupportedPlatform,
    /// `None` matches any host arch and the resolved descriptor reports
    /// `Architecture::Universal`; `Some` pins both the match and the
    /// reported architecture (ReaPack's per-slice DLLs).
    #[serde(default)]
    pub arch: Option<Architecture>,
    #[serde(default)]
    pub name_prefix: Option<String>,
    #[serde(default)]
    pub name_suffix: Option<String>,
    #[serde(default)]
    pub exact_name: Option<String>,
    /// Per-asset override of [`GithubReleaseSpec::artifact_kind`]. Lets a
    /// multi-platform package ship different kinds per slice (Surge XT's
    /// Windows `Installer` vs macOS `DiskImage`). `None` falls back to the
    /// spec-wide kind.
    #[serde(default)]
    pub artifact_kind: Option<GithubArtifactKind>,
}

impl AssetSelector {
    /// Whether `asset_name` satisfies this selector.
    pub fn matches_asset(&self, asset_name: &str) -> bool {
        if let Some(exact) = &self.exact_name {
            return asset_name == exact;
        }
        let prefix_ok = self
            .name_prefix
            .as_ref()
            .is_none_or(|prefix| asset_name.starts_with(prefix));
        let suffix_ok = self
            .name_suffix
            .as_ref()
            .is_none_or(|suffix| asset_name.ends_with(suffix));
        prefix_ok && suffix_ok
    }
}

/// How a downloaded artifact (a GitHub asset OR a scraped/fixed download) is
/// handled. Maps 1:1 onto [`crate::artifact::ArtifactKind`]. Shared by both
/// the [`GithubReleaseSpec`] path and the non-GitHub [`HttpArtifactSpec`] path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GithubArtifactKind {
    /// A `.zip` from which the matching plugin file is extracted.
    Archive,
    /// A bare plugin file dropped in place (ReaPack's `.dll`/`.dylib`).
    ExtensionBinary,
    /// A vendor `.exe`/`.pkg` installer run by `run_upstream_installer`
    /// (REAPER, SWS, OSARA-win, Surge XT-win).
    Installer,
    /// A macOS `.dmg` (REAPER, SWS-mac, Surge XT-mac).
    DiskImage,
    /// A `.7z` archive (FFmpeg shared builds). Extracted by the dedicated 7z
    /// path since the `zip` crate can't read it.
    SevenZipArchive,
}

/// Where a data-driven package installs its file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum InstallDestination {
    /// `<resource>/UserPlugins/` — the default for REAPER extensions.
    #[default]
    UserPlugins,
    /// `%LOCALAPPDATA%\Programs\Common\CLAP` — the per-user CLAP folder
    /// (app2clap), outside any REAPER resource path.
    WindowsClapDir,
}

/// Data-driven artifact (download) resolution for packages that are NOT a
/// single GitHub release: REAPER (reaper.fm scrape), OSARA (snapshot-index
/// scrape), SWS (home-page scrape) and FFmpeg (per-arch dual source). Read
/// only by [`crate::artifact`]; the version side keeps using [`VersionRule`]
/// and the resolved version is stamped onto the descriptor.
///
/// Every target is keyed by `(platform, match_arches)`. The first target
/// whose platform matches and whose `match_arches` contains the (already
/// canonicalized) dispatch arch wins. No matching target yields
/// `NoArtifactFound` — this is how SWS rejects Windows-on-ARM and FFmpeg
/// rejects x86/macOS, with no per-package Rust. A package sets EXACTLY ONE of
/// `github_release` / `http_artifact` / `hfs_listing` (enforced by the
/// load-time validator).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HttpArtifactSpec {
    pub targets: Vec<HttpArtifactTarget>,
}

/// One `(platform, arches)` → download rule.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HttpArtifactTarget {
    pub platform: SupportedPlatform,
    /// Input dispatch arches (post-`canonicalize_dispatch_arch`) this target
    /// serves. The arch-collapse fan-in lives here: REAPER-win lists
    /// `["x64","universal","unknown"]` on its x64 target. `universal`/`unknown`
    /// are accepted belt-and-suspenders even though canonicalization usually
    /// rewrites them to a concrete host slice first.
    pub match_arches: Vec<Architecture>,
    /// Architecture stamped on the resulting descriptor (REWRITES arch:
    /// win x64-target → `x64`, mac universal-target → `universal`, osara →
    /// `universal`, ffmpeg-arm64 → `arm64`). Independent of `match_arches`.
    pub report_arch: Architecture,
    pub artifact_kind: GithubArtifactKind,
    /// How the download URL + file name are produced.
    pub source: HttpArtifactSource,
}

/// The shapes the snowflakes need. Externally tagged (`serde` tag = variant).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HttpArtifactSource {
    /// Scrape an HTML page for the FIRST `<a href>` whose value matches.
    /// Covers REAPER, OSARA, SWS. The matched href becomes the download URL
    /// via `absolute_url(base_url, href)`; the file name is its basename. The
    /// version comes from the package's [`VersionRule`] and is stored on the
    /// descriptor only (never interpolated).
    ScrapeHref {
        page_url: String,
        base_url: String,
        /// Anchored predicate over the href. `contains` is an AND-list;
        /// `not_contains` disambiguates REAPER's x86 `-install.exe` (a
        /// substring of the x64/arm64 hrefs) so matching is order-INDEPENDENT
        /// instead of relying on document order; `ends_with` pins the
        /// extension.
        #[serde(rename = "match")]
        href_match: HrefMatch,
    },
    /// A fixed download URL (no version interpolation). Covers FFmpeg x64
    /// (Gyan redirector). `file_name` overrides the URL basename so the cache
    /// layout stays stable if the redirector path changes.
    FixedUrl {
        url: String,
        #[serde(default)]
        file_name: Option<String>,
    },
    /// Highest *stable* GitHub release whose major == `supported_major`, then
    /// the asset matching `asset`. Covers FFmpeg arm64 (tordona). The version
    /// is the picked release's, NOT the package `VersionRule`. Distinct from
    /// `github_release` because tags are plain `MAJOR.MINOR.PATCH` and
    /// "newest within a pinned major" isn't expressible by
    /// [`GithubReleaseSelector`].
    GithubReleaseMaxMajor {
        /// `owner/name`, e.g. `tordona/ffmpeg-win-arm64`.
        repo: String,
        /// Major-version gate; must equal `FFMPEG_SUPPORTED_MAJOR`.
        supported_major: u64,
        asset: AssetMatch,
    },
}

/// Anchored href predicate for [`HttpArtifactSource::ScrapeHref`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HrefMatch {
    #[serde(default)]
    pub contains: Vec<String>,
    #[serde(default)]
    pub not_contains: Vec<String>,
    #[serde(default)]
    pub ends_with: Option<String>,
}

impl HrefMatch {
    /// Whether `href` satisfies every clause (all `contains`, no
    /// `not_contains`, optional `ends_with`).
    pub fn matches(&self, href: &str) -> bool {
        self.contains.iter().all(|needle| href.contains(needle))
            && self
                .not_contains
                .iter()
                .all(|needle| !href.contains(needle))
            && self.ends_with.as_ref().is_none_or(|s| href.ends_with(s))
    }
}

/// Asset predicate for [`HttpArtifactSource::GithubReleaseMaxMajor`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssetMatch {
    #[serde(default)]
    pub contains: Vec<String>,
    #[serde(default)]
    pub ends_with: Option<String>,
}

impl AssetMatch {
    pub fn matches(&self, name: &str) -> bool {
        self.contains.iter().all(|needle| name.contains(needle))
            && self.ends_with.as_ref().is_none_or(|s| name.ends_with(s))
    }
}

/// Data-driven definition of a package distributed through a rejetto HFS
/// folder listing (`hoard.reaperaccessibility.com`). Like [`GithubReleaseSpec`]
/// it drives BOTH the version side ([`crate::latest`]) and the download side
/// ([`crate::artifact`]) from one source: the engine reads the folder listing,
/// picks the highest-version installer, and uses it for both. Covers JAWS-for-
/// REAPER scripts — the one package that isn't a web page or GitHub release.
/// The HFS `get_file_list` protocol and the `.exe` highest-version pick stay as
/// engine helpers selected by this block (the same "spec selects an irreducible
/// helper" pattern as [`HttpArtifactSource::GithubReleaseMaxMajor`]).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HfsListingSpec {
    /// rejetto HFS server root, e.g. `https://hoard.reaperaccessibility.com`.
    pub base: String,
    /// URL-encoded folder path under the root whose listing is read.
    pub folder: String,
    /// How the picked file is handled (JAWS ships an `Installer` `.exe`).
    pub artifact_kind: GithubArtifactKind,
}

/// Data-driven latest-version discovery for packages that don't come from a
/// GitHub release. Each variant fetches a URL and extracts a version, so a
/// snowflake's version side is manifest data rather than a per-package Rust
/// parser. Serializes as `{ "html": { … } }` / `{ "json": { … } }` /
/// `{ "plain_text": { … } }`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VersionRule {
    /// Fetch `url`, match `pattern` (a regex) against the body, and build the
    /// version from the capture groups via `format` (default `"{1}"`, i.e.
    /// the first group). Covers HTML scrapes like REAPER's
    /// `Version ([0-9.]+)` and SWS's two-group `base` + `#build`
    /// (`format: "{1}.{2}"`).
    Html {
        url: String,
        pattern: String,
        #[serde(default = "default_capture_format")]
        format: String,
    },
    /// Fetch `url` (JSON) and read the string at `pointer` (an RFC 6901 JSON
    /// pointer, e.g. `/version`). Covers OSARA's `update.json`.
    Json { url: String, pointer: String },
    /// Fetch `url` and parse the trimmed body as a version. Covers FFmpeg's
    /// Gyan `*.ver` plain-text endpoint.
    PlainText { url: String },
}

fn default_capture_format() -> String {
    "{1}".to_string()
}

/// A detection probe. Listed in `detectors` per package and run by the
/// detection engine in order, so the manifest declares both *which* probes
/// apply and their fallback order. `RabbitReceipt` (authoritative) and
/// `UserPluginFile` (file presence) are special bookends; the rest are
/// version probes / out-of-tree detectors, some carrying their parameters
/// as data (registry name, scan pattern), some selecting a bespoke engine
/// helper whose domain logic is irreducible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PackageDetector {
    /// RABBIT's own install receipt — authoritative version, checked first.
    RabbitReceipt,
    /// A matching file's presence in the package's install destination.
    UserPluginFile,
    /// The detected file's PE / Mach-O version metadata.
    FileVersionMetadata,
    /// The ReaPack local registry's recorded version for the file.
    ReapackRegistry,
    /// The Windows uninstall-registry `DisplayVersion` for `display_name`
    /// (e.g. OSARA's installer entry, shown in Programs and Features).
    UninstallDisplayVersion { display_name: String },
    /// A best-effort scan of the detected binary for a version string matched
    /// by `pattern` (regex, capture group 1), reported as `label` with
    /// `note`. Generalizes the OSARA / ReaKontrol / SWS / ReaPack embedded-
    /// version-string scanners (each just a different anchored pattern).
    BinaryVersionString {
        pattern: String,
        label: String,
        note: String,
    },
    /// FFmpeg's bespoke 3-probe detector (`ffmpeg.exe` StringFileInfo →
    /// binary banner scan → `avformat-XX` filename → libavformat-major map).
    /// The map (`lib_major - 54`) and probe orchestration stay in the engine.
    FfmpegLibavformat,
    /// JAWS-for-REAPER scripts: follow the Programs-and-Features uninstall
    /// key to the vendor `Uninstall.exe` and read its FileVersion resource.
    JawsUninstallExe,
    /// Surge XT: the Inno Setup uninstall `DisplayVersion` plus the system
    /// VST3 bundle's file metadata.
    SurgeVendorFiles,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InstallStep {
    RunUpstreamInstaller,
    CopyUserPluginBinary,
    CopyKeymap,
    InstallReapackPackage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UninstallStep {
    RemoveUserPluginBinary,
    RemoveKeymap,
    RemoveReapackPackage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum BackupPolicy {
    #[default]
    None,
    BackupOverwrittenFiles,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlatformSuffixes {
    #[serde(default)]
    pub windows: Vec<String>,
    #[serde(default)]
    pub macos: Vec<String>,
}

pub fn builtin_package_specs(platform: Platform) -> Vec<PackageSpec> {
    embedded_package_manifest()
        .packages
        .iter()
        .filter(|package| package.supports_platform(platform))
        .map(|package| package.to_package_spec(platform))
        .collect()
}

pub fn default_desired_package_ids() -> Vec<String> {
    default_desired_package_ids_for_host(&detect_host_capabilities())
}

/// Same as [`default_desired_package_ids`] but with an explicit host
/// snapshot, so tests can pin "Komplete Kontrol detected"/"missing" without
/// touching the real registry/filesystem. Honors `recommended_when` so a
/// host-conditional package (e.g. ReaKontrol when Komplete Kontrol is
/// detected) lands in the default desired set even though its manifest
/// baseline is `recommended: false`.
pub fn default_desired_package_ids_for_host(host: &HostCapabilities) -> Vec<String> {
    embedded_package_manifest()
        .packages
        .iter()
        .filter(|package| {
            package.recommended || package.recommended_when.is_some_and(|cap| host.has(cap))
        })
        .map(|package| package.id.clone())
        .collect()
}

/// Host-side facts the wizard / CLI consult to gate or escalate optional
/// packages. Lives in `rabbit-core` so callers (CLI, GUI) can share one
/// detection path. Probed via [`detect_host_capabilities`].
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct HostCapabilities {
    /// JAWS-for-Windows is installed for the current user. Gates the
    /// "JAWS-for-REAPER scripts" package's *visibility* via
    /// [`host_supports_package`].
    pub jaws_installed: bool,
    /// Native Instruments Komplete Kontrol is installed. Promotes
    /// ReaKontrol from `recommended: false` to recommended-by-default via
    /// [`effective_recommended`] without changing visibility.
    pub komplete_kontrol_installed: bool,
}

impl HostCapabilities {
    /// `true` iff `capability` is present on this host.
    pub fn has(&self, capability: HostCapability) -> bool {
        match capability {
            HostCapability::JawsInstalled => self.jaws_installed,
            HostCapability::KompleteKontrolInstalled => self.komplete_kontrol_installed,
        }
    }
}

/// Named host facilities a manifest entry can reference. Today this enum
/// drives [`PackageSpec::recommended_when`], but its design (one variant per
/// `HostCapabilities` field) is shared so future manifest fields can opt
/// into the same vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HostCapability {
    JawsInstalled,
    KompleteKontrolInstalled,
}

/// Snapshot the runtime host facts that gate or escalate optional packages.
pub fn detect_host_capabilities() -> HostCapabilities {
    HostCapabilities {
        jaws_installed: rabbit_platform::is_jaws_installed(),
        komplete_kontrol_installed: rabbit_platform::is_komplete_kontrol_installed(),
    }
}

/// `true` when the host can meaningfully receive `spec`. Returns `false` for
/// packages whose `package_kind` requires a host facility that isn't present
/// — today only [`PackageKind::ScreenReaderScripts`] needs this filter, and
/// it's a JAWS-presence check.
pub fn host_supports_package(spec: &PackageSpec, host: &HostCapabilities) -> bool {
    match spec.package_kind {
        PackageKind::ScreenReaderScripts => host.jaws_installed,
        PackageKind::ReaperApp
        | PackageKind::UserPluginBinary
        | PackageKind::Keymap
        | PackageKind::ReapackPackage => true,
    }
}

/// Effective recommended state for `spec`, given the current host. Equals
/// `spec.recommended` unless `spec.recommended_when` names a present
/// capability, in which case it escalates to `true`. Use this everywhere
/// a "should this auto-tick / be in the default desired set?" decision is
/// made, not the raw [`PackageSpec::recommended`] field.
pub fn effective_recommended(spec: &PackageSpec, host: &HostCapabilities) -> bool {
    spec.recommended || spec.recommended_when.is_some_and(|cap| host.has(cap))
}

/// Build the package manifest by parsing every embedded per-package file
/// (gathered by build.rs) into an [`EmbeddedPackageSpec`]. Files are already
/// sorted by name (numeric-prefix order); the result keeps that order so the
/// wizard's package list is stable.
pub fn embedded_package_manifest() -> PackageManifest {
    let packages = EMBEDDED_PACKAGE_SOURCES
        .iter()
        .map(|(name, source)| {
            let spec = parse_embedded_package_spec(source)
                .unwrap_or_else(|err| panic!("embedded package file {name} should parse: {err}"));
            if let Err(message) = validate_package_spec(&spec) {
                panic!("embedded package file {name} is invalid: {message}");
            }
            spec
        })
        .collect();
    PackageManifest {
        schema_version: PACKAGE_MANIFEST_SCHEMA_VERSION,
        packages,
    }
}

/// Validate a parsed package spec's artifact configuration. The embedded
/// manifest is first-party data gathered at compile time, so a violation is a
/// developer error surfaced as a panic at startup/test time (alongside the
/// parse panic above) rather than a download-time failure.
///
/// Rules: a package declares its download via at most ONE of `github_release`
/// / `http_artifact` / `hfs_listing`; and every `github_release` asset must
/// resolve an artifact kind from its own `artifact_kind` or the spec-wide
/// fallback (so the resolver never has to guess a kind).
pub fn validate_package_spec(spec: &EmbeddedPackageSpec) -> Result<(), String> {
    let sources = [
        ("github_release", spec.github_release.is_some()),
        ("http_artifact", spec.http_artifact.is_some()),
        ("hfs_listing", spec.hfs_listing.is_some()),
    ];
    let set: Vec<&str> = sources
        .iter()
        .filter(|(_, present)| *present)
        .map(|(name, _)| *name)
        .collect();
    if set.len() > 1 {
        return Err(format!(
            "sets multiple artifact sources ({}); a package must declare exactly one",
            set.join(", ")
        ));
    }

    if let Some(github_release) = &spec.github_release {
        for (index, selector) in github_release.assets.iter().enumerate() {
            if selector
                .artifact_kind
                .or(github_release.artifact_kind)
                .is_none()
            {
                return Err(format!(
                    "github_release asset #{index} has no artifact_kind and the spec sets no fallback artifact_kind"
                ));
            }
        }
    }

    Ok(())
}

/// Total size in bytes of the embedded per-package manifest files. Reported
/// by the portability self-check as a rough "the embedded manifest is intact"
/// signal.
pub fn embedded_package_manifest_bytes() -> usize {
    EMBEDDED_PACKAGE_SOURCES
        .iter()
        .map(|(_, source)| source.len())
        .sum()
}

/// Parse a single per-package manifest file into an [`EmbeddedPackageSpec`].
pub fn parse_embedded_package_spec(source: &str) -> Result<EmbeddedPackageSpec, serde_json::Error> {
    serde_json::from_str(source)
}

/// Parse a combined `{ "schema_version", "packages": [...] }` manifest
/// document. Retained for callers that load an external/override manifest;
/// the embedded manifest is now assembled from per-package files.
pub fn parse_package_manifest(source: &str) -> Result<PackageManifest, serde_json::Error> {
    serde_json::from_str(source)
}

pub fn package_specs_by_id(platform: Platform) -> BTreeMap<String, PackageSpec> {
    builtin_package_specs(platform)
        .into_iter()
        .map(|spec| (spec.id.clone(), spec))
        .collect()
}

impl EmbeddedPackageSpec {
    pub fn supports_platform(&self, platform: Platform) -> bool {
        self.supported_platforms
            .iter()
            .any(|supported| supported.matches_platform(platform))
    }

    fn to_package_spec(&self, platform: Platform) -> PackageSpec {
        PackageSpec {
            id: self.id.clone(),
            display_name: self.display_name.clone(),
            display_name_key: self.display_name_key.clone(),
            display_description_key: self.display_description_key.clone(),
            package_kind: self.package_kind,
            required: self.required,
            recommended: self.recommended,
            recommended_when: self.recommended_when,
            requires_user_acknowledgement: self.requires_user_acknowledgement,
            requires_standard_install: self.requires_standard_install,
            supported_platforms: self.supported_platforms.clone(),
            supported_architectures: self.supported_architectures.clone(),
            version: self.version.clone(),
            detectors: self.detectors.clone(),
            install_steps: self.install_steps.clone(),
            uninstall_steps: self.uninstall_steps.clone(),
            backup_policy: self.backup_policy,
            user_plugin_prefixes: self.user_plugin_prefixes.clone(),
            user_plugin_suffixes: self.user_plugin_suffixes.for_platform(platform),
            category: self.category,
            github_release: self.github_release.clone(),
            http_artifact: self.http_artifact.clone(),
            hfs_listing: self.hfs_listing.clone(),
        }
    }
}

impl PackageSpec {
    pub fn supports_platform(&self, platform: Platform) -> bool {
        self.supported_platforms
            .iter()
            .any(|supported| supported.matches_platform(platform))
    }

    pub fn supports_architecture(&self, architecture: Architecture) -> bool {
        self.supported_architectures.contains(&architecture)
            || self
                .supported_architectures
                .contains(&Architecture::Universal)
    }
}

impl SupportedPlatform {
    pub fn matches_platform(self, platform: Platform) -> bool {
        matches!(
            (self, platform),
            (Self::Windows, Platform::Windows) | (Self::Macos, Platform::MacOs)
        )
    }
}

impl PlatformSuffixes {
    fn for_platform(&self, platform: Platform) -> Vec<String> {
        match platform {
            Platform::Windows => self.windows.clone(),
            Platform::MacOs => self.macos.clone(),
        }
    }
}

fn all_supported_platforms() -> Vec<SupportedPlatform> {
    vec![SupportedPlatform::Windows, SupportedPlatform::Macos]
}

fn all_supported_architectures() -> Vec<Architecture> {
    vec![
        Architecture::X86,
        Architecture::X64,
        Architecture::Arm64,
        Architecture::Arm64Ec,
        Architecture::Universal,
    ]
}

#[cfg(test)]
mod tests {
    use crate::model::{Architecture, Platform};
    use crate::package::{
        BackupPolicy, GithubArtifactKind, GithubReleaseSelector, HostCapabilities, HostCapability,
        InstallDestination, InstallStep, PACKAGE_JAWS_SCRIPTS, PACKAGE_OSARA, PACKAGE_REAKONTROL,
        PACKAGE_REAPACK, PACKAGE_REAPER, PACKAGE_SURGE_XT, PACKAGE_SWS, PackageDetector,
        PackageKind, SupportedPlatform, VersionRule, VersionSource, builtin_package_specs,
        default_desired_package_ids_for_host, embedded_package_manifest,
        embedded_package_manifest_bytes, package_specs_by_id, parse_package_manifest,
    };

    #[test]
    fn parses_embedded_package_manifest() {
        let manifest = embedded_package_manifest();

        assert_eq!(manifest.schema_version, 1);
        assert_eq!(manifest.packages.len(), 9);
        assert!(
            manifest
                .packages
                .iter()
                .any(|package| package.id == PACKAGE_REAPER)
        );
        assert!(
            manifest
                .packages
                .iter()
                .any(|package| package.id == PACKAGE_OSARA)
        );
        assert!(
            manifest
                .packages
                .iter()
                .any(|package| package.id == PACKAGE_REAKONTROL)
        );
        let reakontrol = manifest
            .packages
            .iter()
            .find(|package| package.id == PACKAGE_REAKONTROL)
            .unwrap();
        assert_eq!(reakontrol.package_kind, PackageKind::UserPluginBinary);
        // ReaKontrol is data-driven via a `github_release` block.
        let github = reakontrol
            .github_release
            .as_ref()
            .expect("reakontrol uses a github_release block");
        assert_eq!(github.repo, "jcsteh/reaKontrol");
        assert!(matches!(github.release, GithubReleaseSelector::Latest));
        assert!(matches!(
            github.version_from,
            VersionSource::AssetName {
                strip_trailing_dot_segment: true
            }
        ));
        assert_eq!(github.artifact_kind, Some(GithubArtifactKind::Archive));
        assert_eq!(github.install_destination, InstallDestination::UserPlugins);
        assert_eq!(reakontrol.user_plugin_prefixes, vec!["reaper_kontrol"]);
        assert!(
            reakontrol
                .install_steps
                .contains(&InstallStep::CopyUserPluginBinary)
        );
        assert!(
            reakontrol
                .detectors
                .contains(&PackageDetector::UserPluginFile)
        );
        let reaper = manifest
            .packages
            .iter()
            .find(|package| package.id == PACKAGE_REAPER)
            .unwrap();
        assert_eq!(reaper.package_kind, PackageKind::ReaperApp);
        // REAPER's version is a data-driven HTML rule and its artifact is a
        // data-driven `http_artifact` page scrape.
        assert!(matches!(reaper.version, Some(VersionRule::Html { .. })));
        let reaper_http = reaper.http_artifact.as_ref().expect("reaper http_artifact");
        assert!(reaper_http.targets.iter().any(|target| matches!(
            (target.platform, target.artifact_kind),
            (SupportedPlatform::Windows, GithubArtifactKind::Installer)
        )));
        assert_eq!(reaper.backup_policy, BackupPolicy::None);
        assert!(
            reaper
                .install_steps
                .contains(&InstallStep::RunUpstreamInstaller)
        );
        let osara = manifest
            .packages
            .iter()
            .find(|package| package.id == PACKAGE_OSARA)
            .unwrap();
        assert_eq!(osara.package_kind, PackageKind::UserPluginBinary);
        assert!(matches!(osara.version, Some(VersionRule::Json { .. })));
        assert!(osara.http_artifact.is_some());
        assert_eq!(osara.backup_policy, BackupPolicy::BackupOverwrittenFiles);
        assert!(osara.detectors.contains(&PackageDetector::UserPluginFile));
        assert!(
            osara
                .install_steps
                .contains(&InstallStep::CopyUserPluginBinary)
        );
        // The per-package files were gathered at compile time and are
        // non-empty (build.rs picked them up).
        assert!(embedded_package_manifest_bytes() > 0);
        let jaws = manifest
            .packages
            .iter()
            .find(|package| package.id == PACKAGE_JAWS_SCRIPTS)
            .unwrap();
        assert_eq!(jaws.package_kind, PackageKind::ScreenReaderScripts);
        assert_eq!(jaws.supported_platforms, vec![SupportedPlatform::Windows]);
        // Manifest baseline is "not recommended"; the package escalates to
        // recommended-by-default via `recommended_when: jaws_installed` so
        // it lands in the desired set only on hosts with JAWS detected.
        assert!(!jaws.recommended);
        assert_eq!(jaws.recommended_when, Some(HostCapability::JawsInstalled));
        // JAWS is data-driven via an `hfs_listing` block (rejetto HFS folder),
        // the only package that isn't a web page or GitHub release.
        let jaws_hfs = jaws.hfs_listing.as_ref().expect("jaws uses hfs_listing");
        assert_eq!(jaws_hfs.base, "https://hoard.reaperaccessibility.com");
        assert!(jaws_hfs.folder.contains("JAWS%20Scripts%20by%20Snowman"));
        assert_eq!(jaws_hfs.artifact_kind, GithubArtifactKind::Installer);
        let surge = manifest
            .packages
            .iter()
            .find(|package| package.id == PACKAGE_SURGE_XT)
            .unwrap();
        assert_eq!(surge.package_kind, PackageKind::UserPluginBinary);
        assert_eq!(
            surge.supported_platforms,
            vec![SupportedPlatform::Windows, SupportedPlatform::Macos]
        );
        assert!(!surge.recommended);
        // Surge XT folds into the data-driven `github_release` engine for BOTH
        // version and artifact.
        let surge_github = surge
            .github_release
            .as_ref()
            .expect("surge uses a github_release block");
        assert_eq!(surge_github.repo, "surge-synthesizer/surge");
        assert!(matches!(
            &surge_github.release,
            GithubReleaseSelector::Tag(tag) if tag == "Nightly"
        ));
        assert!(surge_github.artifact_kind.is_none());
        assert!(surge_github.assets.iter().any(|selector| matches!(
            (selector.platform, selector.artifact_kind),
            (
                SupportedPlatform::Windows,
                Some(GithubArtifactKind::Installer)
            )
        )));
        assert!(
            surge
                .install_steps
                .contains(&InstallStep::RunUpstreamInstaller)
        );
        assert!(surge.detectors.contains(&PackageDetector::RabbitReceipt));
        assert!(surge.detectors.contains(&PackageDetector::SurgeVendorFiles));
        assert!(surge.user_plugin_prefixes.is_empty());
    }

    #[test]
    fn builds_platform_specific_package_specs_from_manifest() {
        let windows = package_specs_by_id(Platform::Windows);
        let macos = package_specs_by_id(Platform::MacOs);

        assert_eq!(
            windows[PACKAGE_REAPACK].user_plugin_suffixes,
            vec![".dll".to_string()]
        );
        assert_eq!(
            macos[PACKAGE_REAPACK].user_plugin_suffixes,
            vec![".dylib".to_string()]
        );
        assert_eq!(windows[PACKAGE_SWS].display_name, "SWS Extension");
        assert_eq!(
            windows[PACKAGE_SWS].package_kind,
            PackageKind::UserPluginBinary
        );
        assert!(windows[PACKAGE_SWS].supports_platform(Platform::Windows));
        assert!(windows[PACKAGE_SWS].supports_architecture(Architecture::X64));
    }

    #[test]
    fn default_desired_packages_are_recommended_manifest_packages() {
        // Pin host capabilities so the test result doesn't depend on whether
        // the dev/CI machine happens to have JAWS or Komplete Kontrol
        // installed — both gate JAWS-scripts/ReaKontrol inclusion via
        // `recommended_when`.
        let host = HostCapabilities::default();
        assert_eq!(
            default_desired_package_ids_for_host(&host),
            vec![
                PACKAGE_REAPER.to_string(),
                PACKAGE_OSARA.to_string(),
                PACKAGE_SWS.to_string(),
            ]
        );
    }

    #[test]
    fn default_desired_packages_include_jaws_scripts_when_jaws_is_detected() {
        let host = HostCapabilities {
            jaws_installed: true,
            ..HostCapabilities::default()
        };
        assert!(
            default_desired_package_ids_for_host(&host)
                .iter()
                .any(|id| id == PACKAGE_JAWS_SCRIPTS),
            "JAWS-for-REAPER scripts must escalate to a default-desired \
             package when JAWS is detected on the host"
        );
    }

    #[test]
    fn default_desired_packages_include_reakontrol_when_komplete_kontrol_is_detected() {
        let host = HostCapabilities {
            komplete_kontrol_installed: true,
            ..HostCapabilities::default()
        };
        assert!(
            default_desired_package_ids_for_host(&host)
                .iter()
                .any(|id| id == PACKAGE_REAKONTROL),
            "ReaKontrol must escalate to a default-desired package when \
             Komplete Kontrol is detected on the host"
        );
    }

    #[test]
    fn can_parse_manifest_fixtures_without_code_changes() {
        let manifest = parse_package_manifest(
            r#"{
                "schema_version": 1,
                "packages": [{
                    "id": "example",
                    "display_name": "Example",
                    "display_name_key": "package-example",
                    "display_description_key": "package-example-description",
                    "package_kind": "user_plugin_binary",
                    "required": false,
                    "recommended": false,
                    "supported_platforms": ["windows", "macos"],
                    "supported_architectures": ["x64", "universal"],
                    "version": { "html": { "url": "https://example.test/", "pattern": "v([0-9.]+)" } },
                    "detectors": ["user_plugin_file"],
                    "install_steps": ["copy_user_plugin_binary"],
                    "uninstall_steps": ["remove_user_plugin_binary"],
                    "backup_policy": "backup_overwritten_files",
                    "user_plugin_prefixes": ["reaper_example"],
                    "user_plugin_suffixes": {
                        "windows": [".dll"],
                        "macos": [".dylib"]
                    }
                }]
            }"#,
        )
        .unwrap();

        assert_eq!(manifest.packages[0].id, "example");
        assert_eq!(
            manifest.packages[0].supported_platforms,
            vec![SupportedPlatform::Windows, SupportedPlatform::Macos]
        );
        assert!(builtin_package_specs(Platform::Windows).len() >= 3);
    }

    #[test]
    fn manifest_defaults_support_older_minimal_entries() {
        let manifest = parse_package_manifest(
            r#"{
                "schema_version": 1,
                "packages": [{
                    "id": "minimal",
                    "display_name": "Minimal",
                    "display_name_key": "package-minimal",
                    "display_description_key": "package-minimal-description",
                    "recommended": false,
                    "user_plugin_prefixes": ["reaper_minimal"],
                    "user_plugin_suffixes": {
                        "windows": [".dll"],
                        "macos": [".dylib"]
                    }
                }]
            }"#,
        )
        .unwrap();

        let package = &manifest.packages[0];
        assert_eq!(package.package_kind, PackageKind::UserPluginBinary);
        assert!(!package.required);
        assert_eq!(package.backup_policy, BackupPolicy::None);
        assert!(package.supports_platform(Platform::MacOs));
    }
}
