//! Gathers the per-package manifest files under `embedded/packages/` at
//! compile time so that adding a package is just dropping a new `*.json`
//! file into that directory — no central registry to edit.
//!
//! Emits `EMBEDDED_PACKAGE_SOURCES: &[(&str, &str)]` (filename, JSON body)
//! into `$OUT_DIR/embedded_packages.rs`, which `package.rs` `include!`s.
//! Files are sorted by name, so a numeric prefix (`10-reaper.json`,
//! `20-osara.json`, …) controls wizard display order.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let packages_dir = Path::new(&manifest_dir).join("embedded/packages");

    // Re-run when a file is added, removed, or changed in the directory (the
    // directory entry itself changes when its contents do), and when any
    // individual file changes.
    println!("cargo:rerun-if-changed={}", packages_dir.display());

    let mut files: Vec<_> = fs::read_dir(&packages_dir)
        .unwrap_or_else(|err| panic!("read {}: {err}", packages_dir.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
        .collect();
    files.sort();

    let mut generated = String::from(
        "// @generated by build.rs — embedded per-package manifest files.\n\
         pub static EMBEDDED_PACKAGE_SOURCES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| panic!("non-UTF-8 package file name: {}", path.display()))
            .to_owned();
        let body =
            fs::read_to_string(path).unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
        // `{:?}` emits a correctly-escaped Rust string literal for both the
        // file name and the JSON body (quotes, backslashes, newlines).
        generated.push_str(&format!("    ({name:?}, {body:?}),\n"));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = Path::new(&out_dir).join("embedded_packages.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}
